// all embedded datasets, generated by build.rs into OUT_DIR.
// statics are exported at crate root via main.rs (`pub use data::*`)

// salatmv prayer-time dataset:
// ATOLL_DATA  : &[[&str; 4]; 20]     0:index, 1:eng_name, 2:dhi_name, 3:ar_name
// ISLAND_DATA : &[[&str; 10]; 205]   0:timeset_index, 1:island_index, 2:atoll_index,
//                                    3:eng_name, 4:dhi_name, 5:ar_name, 6:unknown,
//                                    7:latitude, 8:longitude, 9:unknown
// PT_DATA     : &[[u32; 8]; 15372]   0:timeset_index, 1:day, 2:fajr, 3:sun, 4:dhuhur,
//                                    5:asr, 6:magrib, 7:isha
include!(concat!(env!("OUT_DIR"), "/salatmv.rs"));

// geonames world cities (CC-BY 4.0):
// CITIES : &[[&str; 4]]   0:name, 1:country, 2:latitude, 3:longitude
include!(concat!(env!("OUT_DIR"), "/geonames.rs"));
